name: recipes
description: Recipe Finder

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  logging: ^1.2.0
  auto_size_text: ^3.0.0
  flutter_adaptive_scaffold: ^0.1.6
  desktop_window: ^0.4.0
  path: ^1.8.3
  cached_network_image: ^3.2.3
  flutter_slidable: ^3.0.0
  platform: ^3.1.0
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.0.7
  flutter_html: ^3.0.0-beta.2
  lumberdash: ^3.0.0
  colorize_lumberdash: ^3.0.0
  path_provider: ^2.0.15
  flutter_riverpod: ^2.3.6

  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/menubar
      ref: 12decbe0f592e14e03223f6f2c0c7e0e2dbd70a1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  freezed: ^2.4.1

  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/recipe_details.json
    - assets/images/
